### PR TITLE
Adapt to new CryptoStore API

### PR DESCRIPTION
**Pull request by hirschenberger**
see https://github.com/paritytech/substrate/pull/8619

### CODE REVIEW

**Review by adoerr — COMMENTED** [review]
I think, we have a bit of a cyclic dependency issue here. My suggestion to resolve this is:

- Merge the Substrate PR  [#8619](https://github.com/paritytech/substrate/pull/8619) that updates the `SyncCryptoStore` API
- We will bump the BEEFY Substrate dependency to a commit that does include this PR
- The Polkadot companion PR should be done next

**Comment by tomusdrw** [comment]
@adoerr instead of using `branch` for deps maybe let's use `rev` instead? That way we can update BEEFY repo before it lands in substrate master. I'm not willing to break regular substrate release process (merging despite companion failing) long term.

**Comment by adoerr** [comment]
@tomusdrw  using `rev` is an option. In the concrete case, however, I'm not sure this would buy us much. Substrate PR [#8618](https://github.com/paritytech/substrate/pull/8619) is still in review. 

IMO, the issue here is that a Substrate API (`SyncCryptoStore`) has been changed, which is used by both, Polkadot and BEEFY. Polkadot depends on BEEFY as well.

Now, PR's to **use** the new version of the Substrate API have been opened, **before** the API change itself was even accepted to Substrate. IMO those two PR's should have done **after** the API change has been accepted into Substrate. 

Or am I missing something here?

**Comment by ordian** [comment]
I don't see a cyclic dependency (BEEFY doesn't depend on polkadot). It seems for now, we'll have to merge such PRs manually (substrate -> beefy -> polkadot). Long-term, mering BEEFY into substrate/polkadot repo would solve this problem.

**Comment by tomusdrw** [comment]
The main problem is that the companion set up was introduced to make sure that random Substrate PRs don't introduce extra work for Polkadot developers - i.e. every change in Substrate that is breaking Polkadot must have a PR (companion PR) that fixes any incompatibilities. This is ENFORCED by Substrate CI - i.e. the build has to be green before you can merge the PR.

Now with the way BEEFY is integrated right now, if there is a Substrate change that breaks BEEFY code there is no way to create a Polkadot companion PR that would turn green (there is one, but it requires patching all beefy deps in Polkadot, which is quite cumbersome). So the most straightforward solution is to either:
1. Merge Substrate PR with failing Polkadot companion and coordinate on swift update.
2. Do something backward compatible (as suggested [here](https://github.com/paritytech/substrate/pull/8619#pullrequestreview-636450337))
3. Change the process to involve BEEFY repo as well.
4. Create a workaround with patching in Polkadot.
5. Consider #149 to be able to freely switch branches (i.e. depend only on revision).

Long term it's going to be solved by the merge indeed or proper versioning/crates.io deployment, but we should discuss how to deal with such breaking changes short/mid-term.

**Comment by tomusdrw** [comment]
@hirschenberger good news, we are planning to expand the companion PR system to this repo now, so it should be possible to move forward soonish.

**Comment by adoerr** [comment]
Since `BEEFY` is now [part](https://github.com/paritytech/substrate/pull/9833) of Substrate, this PR has become obsolete.

**Pull request closed without merging**
